function tests = TestResolveTensorTaskSelection
tests = functiontests(localfunctions);
end

function testSortsDiscoveredFilesByName(testCase)
temp_dir = createTempTensorDir(testCase);
createTensorStub(temp_dir, 'p4_Vol0.37_K0.0000_Sample_101210_tensor.mat');
createTensorStub(temp_dir, 'p4_Vol0.36_K0.0995_Sample_4982_tensor.mat');
createTensorStub(temp_dir, 'p4gm_Vol0.29_K0.0000_Sample_103302_tensor.mat');

cfg = struct( ...
    'tensor_dir', temp_dir, ...
    'tensor_files', {{}}, ...
    'task_index_start', [], ...
    'task_index_end', [], ...
    'case_name_suffix', '');

selection = ResolveTensorTaskSelection(cfg);

expected = { ...
    fullfile(temp_dir, 'p4_Vol0.36_K0.0995_Sample_4982_tensor.mat'); ...
    fullfile(temp_dir, 'p4_Vol0.37_K0.0000_Sample_101210_tensor.mat'); ...
    fullfile(temp_dir, 'p4gm_Vol0.29_K0.0000_Sample_103302_tensor.mat')};
verifyEqual(testCase, selection.selected_files, expected);
verifyEqual(testCase, selection.effective_start, 1);
verifyEqual(testCase, selection.effective_end, 3);
end

function testPreservesExplicitTensorFilesOrder(testCase)
cfg = struct( ...
    'tensor_dir', '', ...
    'tensor_files', {{ ...
        'z_tensor.mat', ...
        'a_tensor.mat', ...
        'm_tensor.mat'}}, ...
    'task_index_start', [], ...
    'task_index_end', [], ...
    'case_name_suffix', '');

selection = ResolveTensorTaskSelection(cfg);

verifyEqual(testCase, selection.selected_files, cfg.tensor_files(:));
end

function testAppliesInclusiveRange(testCase)
cfg = struct( ...
    'tensor_dir', '', ...
    'tensor_files', {{ ...
        'case_01_tensor.mat', ...
        'case_02_tensor.mat', ...
        'case_03_tensor.mat', ...
        'case_04_tensor.mat'}}, ...
    'task_index_start', 2, ...
    'task_index_end', 3, ...
    'case_name_suffix', '');

selection = ResolveTensorTaskSelection(cfg);

verifyEqual(testCase, selection.selected_files, { ...
    'case_02_tensor.mat'; ...
    'case_03_tensor.mat'});
verifyEqual(testCase, selection.effective_start, 2);
verifyEqual(testCase, selection.effective_end, 3);
end

function testStartOnlyRunsToEnd(testCase)
cfg = struct( ...
    'tensor_dir', '', ...
    'tensor_files', {{ ...
        'case_01_tensor.mat', ...
        'case_02_tensor.mat', ...
        'case_03_tensor.mat'}}, ...
    'task_index_start', 2, ...
    'task_index_end', [], ...
    'case_name_suffix', '');

selection = ResolveTensorTaskSelection(cfg);

verifyEqual(testCase, selection.selected_files, { ...
    'case_02_tensor.mat'; ...
    'case_03_tensor.mat'});
verifyEqual(testCase, selection.effective_start, 2);
verifyEqual(testCase, selection.effective_end, 3);
end

function testClampsRangeEnd(testCase)
cfg = struct( ...
    'tensor_dir', '', ...
    'tensor_files', {{ ...
        'case_01_tensor.mat', ...
        'case_02_tensor.mat', ...
        'case_03_tensor.mat'}}, ...
    'task_index_start', 2, ...
    'task_index_end', 10, ...
    'case_name_suffix', '');

selection = ResolveTensorTaskSelection(cfg);

verifyEqual(testCase, selection.effective_end, 3);
verifyTrue(testCase, selection.end_clamped);
end

function testRejectsStartBeyondTaskCount(testCase)
cfg = struct( ...
    'tensor_dir', '', ...
    'tensor_files', {{'case_01_tensor.mat'}}, ...
    'task_index_start', 2, ...
    'task_index_end', [], ...
    'case_name_suffix', '');

verifyError(testCase, @() ResolveTensorTaskSelection(cfg), ...
    'ResolveTensorTaskSelection:RangeStartOutOfBounds');
end

function testRejectsEndBeforeStart(testCase)
cfg = struct( ...
    'tensor_dir', '', ...
    'tensor_files', {{ ...
        'case_01_tensor.mat', ...
        'case_02_tensor.mat'}}, ...
    'task_index_start', 2, ...
    'task_index_end', 1, ...
    'case_name_suffix', '');

verifyError(testCase, @() ResolveTensorTaskSelection(cfg), ...
    'ResolveTensorTaskSelection:InvalidRangeOrder');
end

function temp_dir = createTempTensorDir(testCase)
temp_dir = tempname;
mkdir(temp_dir);
testCase.addTeardown(@() rmdir(temp_dir, 's'));
end

function createTensorStub(folder, name)
fid = fopen(fullfile(folder, name), 'w');
fclose(fid);
end
