function tests = TestSaveAcousticBandDatasetFile
tests = functiontests(localfunctions);
end

function testWritesSplitFilesOnlyForSelectedStride(testCase)
temp_dir = tempname;
mkdir(temp_dir);
testCase.addTeardown(@() rmdir(temp_dir, 's'));

result = buildStubResult();
cfg = buildStubConfig(temp_dir, 'case_keep', 1);
files = SaveAcousticBandDatasetFile(result, struct(), cfg);

verifyEqual(testCase, exist(files.band_dataset_file, 'file'), 2);
verifyEqual(testCase, exist(files.fields_dataset_file, 'file'), 2);

band_loaded = load(files.band_dataset_file, 'dataset');
verifyFalse(testCase, isfield(band_loaded.dataset, 'fields'));

fields_loaded = load(files.fields_dataset_file, 'fields_dataset');
verifySize(testCase, fields_loaded.fields_dataset.field_data, [128, 128, 50]);
verifyClass(testCase, fields_loaded.fields_dataset.field_data, 'single');
verifySize(testCase, fields_loaded.fields_dataset.selection_ik, [50, 1]);
end

function testSkipsFieldsFileWhenStrideDoesNotMatch(testCase)
temp_dir = tempname;
mkdir(temp_dir);
testCase.addTeardown(@() rmdir(temp_dir, 's'));

result = buildStubResult();
cfg = buildStubConfig(temp_dir, 'case_skip', 2);
files = SaveAcousticBandDatasetFile(result, struct(), cfg);

verifyEqual(testCase, exist(files.band_dataset_file, 'file'), 2);
verifyEqual(testCase, files.fields_dataset_file, '');
end

function result = buildStubResult()
base_resolution = 8;
result = struct();
result.case_id = 'stub_case';
result.band_frequencies_hz = reshape(1:510, [51, 10]);
result.geometry = struct( ...
    'symmetry_group', 'p4', ...
    'xPhysRaw', rand(base_resolution, base_resolution), ...
    'xPhysCanonical', rand(base_resolution, base_resolution), ...
    'solidMaskCanonical', rand(base_resolution, base_resolution) > 0.5, ...
    'solidMaskDisplay', rand(base_resolution, base_resolution) > 0.5, ...
    'voidMaskForComsol', rand(base_resolution, base_resolution) > 0.5, ...
    'displayImage', uint8(rand(base_resolution, base_resolution) * 255), ...
    'solid_volume_fraction', 0.4, ...
    'volume_fraction', 0.4);
result.brillouin_zone = struct( ...
    'high_symmetry_labels', {{'G', 'X', 'M', 'G'}}, ...
    'high_symmetry_points', rand(4, 2), ...
    'k_points', rand(51, 2), ...
    'path_coordinate', linspace(0, 1, 51).', ...
    'tick_coordinate', [0, 0.3, 0.7, 1], ...
    'point_labels', {{'G', 'X', 'M', 'G'}}, ...
    'path_name', 'G-X-M-G');
result.comsol = struct( ...
    'status', repmat("ok", 51, 1), ...
    'mode_fields', struct( ...
        'data', rand(base_resolution, base_resolution, 10, 51), ...
        'expression', 'p', ...
        'status', repmat("ok", 51, 10), ...
        'grid_resolution', [base_resolution, base_resolution], ...
        'x', linspace(0, 1, base_resolution), ...
        'y', linspace(0, 1, base_resolution)), ...
    'periodic_pairs', struct(), ...
    'periodic_x', true, ...
    'periodic_y', true, ...
    'extraction', struct());
result.config = struct();
end

function cfg = buildStubConfig(output_dir, case_id, task_sequence_index)
cfg = AcousticBandConfig( ...
    'output_dir', output_dir, ...
    'case_id', case_id, ...
    'split_band_and_fields_files', true, ...
    'save_fields_for_sample_stride', 10, ...
    'save_fields_for_sample_offset', 1, ...
    'field_sample_count', 50, ...
    'field_sample_k_bins', 10, ...
    'field_sample_band_bins', 5, ...
    'field_output_grid_resolution', 128, ...
    'field_output_dtype', 'single', ...
    'field_sampling_mode', 'stratified_random', ...
    'task_sequence_index', task_sequence_index, ...
    'num_eigenfrequencies', 10, ...
    'total_k_points', 51);
end
