function launch = portable_run_batch(overrides)
%PORTABLE_RUN_BATCH Entry point for portable COMSOL batch generation.

portable_add_paths();
if nargin < 1
    overrides = struct();
elseif isempty(overrides)
    overrides = struct();
elseif ~isstruct(overrides)
    error('portable_run_batch:InvalidOverrides', ...
        'Optional overrides must be a struct.');
end
cfg = portable_batch_config_template(overrides);

if ~exist(cfg.tensor_dir, 'dir') && isempty(cfg.tensor_files)
    error('portable_run_batch:MissingTensorDir', ...
        'tensor_dir does not exist: %s', cfg.tensor_dir);
end

if ~exist(cfg.output_dir, 'dir')
    mkdir(cfg.output_dir);
end

fprintf('Portable batch run configuration:\n');
fprintf('  tensor_dir: %s\n', cfg.tensor_dir);
fprintf('  output_dir: %s\n', cfg.output_dir);
fprintf('  task_index_start: %s\n', optionalIndexText(cfg.task_index_start));
fprintf('  task_index_end: %s\n', optionalIndexText(cfg.task_index_end));
fprintf('  worker_count: %d\n', cfg.worker_count);
fprintf('  parallel_mode: manual COMSOL-with-MATLAB host + per-worker isolated server\n');
fprintf('  worker_launch_mode: %s\n', cfg.worker_launch_mode);
fprintf('  comsol_root: %s\n', cfg.comsol_root);
if isfield(cfg, 'comsol_mli_dir') && ~isempty(cfg.comsol_mli_dir)
    fprintf('  comsol_mli_dir: %s\n', cfg.comsol_mli_dir);
end
fprintf('  enable_worker_comsol_recovery: %d\n', cfg.enable_worker_comsol_recovery);
fprintf('  case_infra_retry_limit: %d\n', cfg.case_infra_retry_limit);
fprintf('  worker_infra_failure_limit: %d\n', cfg.worker_infra_failure_limit);
fprintf('  worker_recovery_backoff_s: %d\n', cfg.worker_recovery_backoff_s);
fprintf('  worker_healthcheck_before_claim: %d\n', cfg.worker_healthcheck_before_claim);
fprintf('  grid_resolution: %d\n', cfg.grid_resolution);
fprintf('  field_grid_resolution: %d\n', cfg.field_grid_resolution);
fprintf('  total_k_points: %d\n', cfg.total_k_points);
fprintf('  num_eigenfrequencies: %d\n', cfg.num_eigenfrequencies);
fprintf('  solid_phase_value: %d\n', cfg.solid_phase_value);

launch = run_band_dataset_batch(cfg);

disp('Worker launch commands (generated by the manual host session):');
disp(launch.commands);
disp('Worker logs:');
disp(launch.log_files);
end

function text = optionalIndexText(value)
if isempty(value)
    text = '<all>';
else
    text = char(string(value));
end
end
